#!/bin/sh

CONFIGDIR=$HOME/.autobuilder.d
CONFIGFILE=$CONFIGDIR/autobuilder.hs

[ -d $CONFIGDIR ] || {
    echo "There is no configuration directory at $CONFIGDIR, an example of this"
    echo "directory can be obtained from http://seereason.com/autobuilder-config."
    exit 1
}
[ -f $CONFIGFILE ] || {
    echo "No configuration file was found at $CONFIGFILE.  an example $CONFIGDIR"
    echo "directory can be obtained from http://seereason.com/autobuilder-config."
    exit 1
}
sudo runhaskell -i$CONFIGDIR $CONFIGFILE $*
